/**
 * Le catalogue des schémas du socle, tel que la démonstration le sert.
 *
 * Ce n'est pas une invention : le contenu est **extrait du socle lui-même** —
 * `StandardSchemas.all(XOF)` —, expressions, rôles et libellés compris. Les libellés de ligne
 * sont sans accent parce que le socle les écrit ainsi dans son code ; les montrer autrement
 * ferait croire à un paramétrage qui n'existe pas.
 *
 * En mode `api`, rien de ce fichier n'est lu : le catalogue vient de
 * `GET /accounting-schemas/standard`, et de là seulement.
 */

import { EvenementSocle } from './schemas.modele';

export const CATALOGUE_DEMONSTRATION: readonly EvenementSocle[] = [
  {
    eventType: 'CASH_DEPOSIT',
    label: 'Versement d\'espèces',
    module: 'OPERATIONS',
    moduleLabel: 'Guichet, virements et moyens de paiement',
    source: 'SOCLE',
    schemaCode: null,
    variables: ['amount'],
    roles: ['cash'],
    derivations: [{ name: 'amt', expression: 'round(amount, 0)' }],
    lines: [
      { account: 'PARAM:cash', direction: 'DEBIT', amount: 'amt', condition: null, label: 'Versement especes' },
      { account: 'CONTRACT', direction: 'CREDIT', amount: 'amt', condition: null, label: 'Versement especes' },
    ],
  },
  {
    eventType: 'CASH_WITHDRAWAL',
    label: 'Retrait d\'espèces',
    module: 'OPERATIONS',
    moduleLabel: 'Guichet, virements et moyens de paiement',
    source: 'SOCLE',
    schemaCode: null,
    variables: ['amount', 'fee', 'tax'],
    roles: ['cash', 'fee_income', 'tax'],
    derivations: [{ name: 'amt', expression: 'round(amount, 0)' }, { name: 'f', expression: 'round(fee, 0)' }, { name: 't', expression: 'round(tax, 0)' }, { name: 'total', expression: 'amt + f + t' }],
    lines: [
      { account: 'CONTRACT', direction: 'DEBIT', amount: 'total', condition: null, label: 'Retrait especes' },
      { account: 'PARAM:cash', direction: 'CREDIT', amount: 'amt', condition: null, label: 'Retrait especes' },
      { account: 'PARAM:fee_income', direction: 'CREDIT', amount: 'f', condition: 'f > 0', label: 'Frais de retrait' },
      { account: 'PARAM:tax', direction: 'CREDIT', amount: 't', condition: 't > 0', label: 'Taxe sur frais' },
    ],
  },
  {
    eventType: 'TRANSFER',
    label: 'Virement interne',
    module: 'OPERATIONS',
    moduleLabel: 'Guichet, virements et moyens de paiement',
    source: 'SOCLE',
    schemaCode: null,
    variables: ['amount', 'fee', 'tax'],
    roles: ['destination', 'fee_income', 'tax'],
    derivations: [{ name: 'amt', expression: 'round(amount, 0)' }, { name: 'f', expression: 'round(fee, 0)' }, { name: 't', expression: 'round(tax, 0)' }, { name: 'total', expression: 'amt + f + t' }],
    lines: [
      { account: 'CONTRACT', direction: 'DEBIT', amount: 'total', condition: null, label: 'Virement emis' },
      { account: 'PARAM:destination', direction: 'CREDIT', amount: 'amt', condition: null, label: 'Virement recu' },
      { account: 'PARAM:fee_income', direction: 'CREDIT', amount: 'f', condition: 'f > 0', label: 'Frais de virement' },
      { account: 'PARAM:tax', direction: 'CREDIT', amount: 't', condition: 't > 0', label: 'Taxe sur frais' },
    ],
  },
  {
    eventType: 'PAYMENT_ORDER',
    label: 'Paiement émis',
    module: 'OPERATIONS',
    moduleLabel: 'Guichet, virements et moyens de paiement',
    source: 'SOCLE',
    schemaCode: null,
    variables: ['amount', 'fee', 'tax'],
    roles: ['clearing', 'fee_income', 'tax'],
    derivations: [{ name: 'amt', expression: 'round(amount, 0)' }, { name: 'f', expression: 'round(fee, 0)' }, { name: 't', expression: 'round(tax, 0)' }, { name: 'total', expression: 'amt + f + t' }],
    lines: [
      { account: 'CONTRACT', direction: 'DEBIT', amount: 'total', condition: null, label: 'Paiement emis' },
      { account: 'PARAM:clearing', direction: 'CREDIT', amount: 'amt', condition: null, label: 'Paiement a regler' },
      { account: 'PARAM:fee_income', direction: 'CREDIT', amount: 'f', condition: 'f > 0', label: 'Frais de paiement' },
      { account: 'PARAM:tax', direction: 'CREDIT', amount: 't', condition: 't > 0', label: 'Taxe sur frais' },
    ],
  },
  {
    eventType: 'CHEQUE_BOOK_FEE',
    label: 'Frais de chéquier',
    module: 'OPERATIONS',
    moduleLabel: 'Guichet, virements et moyens de paiement',
    source: 'SOCLE',
    schemaCode: null,
    variables: ['fee', 'tax'],
    roles: ['fee_income', 'tax'],
    derivations: [{ name: 'f', expression: 'round(fee, 0)' }, { name: 't', expression: 'round(tax, 0)' }, { name: 'total', expression: 'f + t' }],
    lines: [
      { account: 'CONTRACT', direction: 'DEBIT', amount: 'total', condition: null, label: 'Frais de chequier' },
      { account: 'PARAM:fee_income', direction: 'CREDIT', amount: 'f', condition: null, label: 'Frais de chequier' },
      { account: 'PARAM:tax', direction: 'CREDIT', amount: 't', condition: 't > 0', label: 'Taxe sur frais' },
    ],
  },
  {
    eventType: 'CHEQUE_PAYMENT',
    label: 'Paiement d\'un chèque émis',
    module: 'OPERATIONS',
    moduleLabel: 'Guichet, virements et moyens de paiement',
    source: 'SOCLE',
    schemaCode: null,
    variables: ['amount'],
    roles: ['counterparty'],
    derivations: [{ name: 'amt', expression: 'round(amount, 0)' }],
    lines: [
      { account: 'CONTRACT', direction: 'DEBIT', amount: 'amt', condition: null, label: 'Cheque paye' },
      { account: 'PARAM:counterparty', direction: 'CREDIT', amount: 'amt', condition: null, label: 'Cheque paye' },
    ],
  },
  {
    eventType: 'CHEQUE_DEPOSIT',
    label: 'Remise de chèque',
    module: 'OPERATIONS',
    moduleLabel: 'Guichet, virements et moyens de paiement',
    source: 'SOCLE',
    schemaCode: null,
    variables: ['amount'],
    roles: ['collection'],
    derivations: [{ name: 'amt', expression: 'round(amount, 0)' }],
    lines: [
      { account: 'PARAM:collection', direction: 'DEBIT', amount: 'amt', condition: null, label: 'Cheque a l\'encaissement' },
      { account: 'CONTRACT', direction: 'CREDIT', amount: 'amt', condition: null, label: 'Remise de cheque sauf bonne fin' },
    ],
  },
  {
    eventType: 'DIRECT_DEBIT',
    label: 'Prélèvement reçu',
    module: 'OPERATIONS',
    moduleLabel: 'Guichet, virements et moyens de paiement',
    source: 'SOCLE',
    schemaCode: null,
    variables: ['amount', 'fee', 'tax'],
    roles: ['creditor', 'fee_income', 'tax'],
    derivations: [{ name: 'amt', expression: 'round(amount, 0)' }, { name: 'f', expression: 'round(fee, 0)' }, { name: 't', expression: 'round(tax, 0)' }, { name: 'total', expression: 'amt + f + t' }],
    lines: [
      { account: 'CONTRACT', direction: 'DEBIT', amount: 'total', condition: null, label: 'Prelevement' },
      { account: 'PARAM:creditor', direction: 'CREDIT', amount: 'amt', condition: null, label: 'Prelevement recu' },
      { account: 'PARAM:fee_income', direction: 'CREDIT', amount: 'f', condition: 'f > 0', label: 'Frais de prelevement' },
      { account: 'PARAM:tax', direction: 'CREDIT', amount: 't', condition: 't > 0', label: 'Taxe sur frais' },
    ],
  },
  {
    eventType: 'DIRECT_DEBIT_ISSUE',
    label: 'Prélèvement émis',
    module: 'OPERATIONS',
    moduleLabel: 'Guichet, virements et moyens de paiement',
    source: 'SOCLE',
    schemaCode: null,
    variables: ['amount'],
    roles: ['collection'],
    derivations: [{ name: 'amt', expression: 'round(amount, 0)' }],
    lines: [
      { account: 'PARAM:collection', direction: 'DEBIT', amount: 'amt', condition: null, label: 'Prelevement a l\'encaissement' },
      { account: 'CONTRACT', direction: 'CREDIT', amount: 'amt', condition: null, label: 'Prelevement emis sauf bonne fin' },
    ],
  },
  {
    eventType: 'DIRECT_DEBIT_FEE',
    label: 'Frais de prélèvement émis',
    module: 'OPERATIONS',
    moduleLabel: 'Guichet, virements et moyens de paiement',
    source: 'SOCLE',
    schemaCode: null,
    variables: ['fee', 'tax'],
    roles: ['fee_income', 'tax'],
    derivations: [{ name: 'f', expression: 'round(fee, 0)' }, { name: 't', expression: 'round(tax, 0)' }, { name: 'total', expression: 'f + t' }],
    lines: [
      { account: 'CONTRACT', direction: 'DEBIT', amount: 'total', condition: null, label: 'Frais de prelevement' },
      { account: 'PARAM:fee_income', direction: 'CREDIT', amount: 'f', condition: null, label: 'Frais de prelevement' },
      { account: 'PARAM:tax', direction: 'CREDIT', amount: 't', condition: 't > 0', label: 'Taxe sur frais' },
    ],
  },
  {
    eventType: 'LOAN_DISBURSEMENT',
    label: 'Déblocage de crédit',
    module: 'LOAN',
    moduleLabel: 'Crédit',
    source: 'SOCLE',
    schemaCode: null,
    variables: ['principal', 'upfront_fees'],
    roles: ['settlement', 'fee_income'],
    derivations: [{ name: 'capital', expression: 'round(principal, 0)' }, { name: 'frais', expression: 'min(round(upfront_fees, 0), capital)' }, { name: 'net', expression: 'capital - frais' }],
    lines: [
      { account: 'CONTRACT', direction: 'DEBIT', amount: 'capital', condition: null, label: 'Deblocage du credit' },
      { account: 'PARAM:settlement', direction: 'CREDIT', amount: 'net', condition: 'net > 0', label: 'Mise a disposition des fonds' },
      { account: 'PARAM:fee_income', direction: 'CREDIT', amount: 'frais', condition: 'frais > 0', label: 'Frais de dossier' },
    ],
  },
  {
    eventType: 'LOAN_TRANCHE_RELEASE',
    label: 'Déblocage d\'une tranche',
    module: 'LOAN',
    moduleLabel: 'Crédit',
    source: 'SOCLE',
    schemaCode: null,
    variables: ['amount', 'upfront_fees'],
    roles: ['settlement', 'fee_income'],
    derivations: [{ name: 'capital', expression: 'round(amount, 0)' }, { name: 'frais', expression: 'min(round(upfront_fees, 0), capital)' }, { name: 'net', expression: 'capital - frais' }],
    lines: [
      { account: 'CONTRACT', direction: 'DEBIT', amount: 'capital', condition: null, label: 'Deblocage de tranche' },
      { account: 'PARAM:settlement', direction: 'CREDIT', amount: 'net', condition: 'net > 0', label: 'Mise a disposition des fonds' },
      { account: 'PARAM:fee_income', direction: 'CREDIT', amount: 'frais', condition: 'frais > 0', label: 'Frais de dossier' },
    ],
  },
  {
    eventType: 'LOAN_INTERIM_INTEREST',
    label: 'Intérêts intercalaires',
    module: 'LOAN',
    moduleLabel: 'Crédit',
    source: 'SOCLE',
    schemaCode: null,
    variables: ['interest', 'tax'],
    roles: ['accrued_receivable', 'interest_income', 'tax_payable'],
    derivations: [{ name: 'i', expression: 'round(interest, 0)' }, { name: 't', expression: 'round(tax, 0)' }, { name: 'total', expression: 'i + t' }],
    lines: [
      { account: 'PARAM:accrued_receivable', direction: 'DEBIT', amount: 'total', condition: null, label: 'Interets intercalaires exigibles' },
      { account: 'PARAM:interest_income', direction: 'CREDIT', amount: 'i', condition: 'i > 0', label: 'Interets de la periode de mobilisation' },
      { account: 'PARAM:tax_payable', direction: 'CREDIT', amount: 't', condition: 't > 0', label: 'Taxe collectee' },
    ],
  },
  {
    eventType: 'LOAN_INSTALMENT_DUE',
    label: 'Échéance exigible',
    module: 'LOAN',
    moduleLabel: 'Crédit',
    source: 'SOCLE',
    schemaCode: null,
    variables: ['interest', 'insurance', 'fee', 'tax'],
    roles: ['accrued_receivable', 'accrued_interest', 'insurance_income', 'fee_income', 'tax_payable'],
    derivations: [{ name: 'i', expression: 'round(interest, 0)' }, { name: 's', expression: 'round(insurance, 0)' }, { name: 'f', expression: 'round(fee, 0)' }, { name: 't', expression: 'round(tax, 0)' }, { name: 'charges', expression: 'i + s + f + t' }],
    lines: [
      { account: 'PARAM:accrued_receivable', direction: 'DEBIT', amount: 'charges', condition: null, label: 'Echeance exigible' },
      { account: 'PARAM:accrued_interest', direction: 'CREDIT', amount: 'i', condition: 'i > 0', label: 'Interets courus repris' },
      { account: 'PARAM:insurance_income', direction: 'CREDIT', amount: 's', condition: 's > 0', label: 'Assurance' },
      { account: 'PARAM:fee_income', direction: 'CREDIT', amount: 'f', condition: 'f > 0', label: 'Frais de dossier' },
      { account: 'PARAM:tax_payable', direction: 'CREDIT', amount: 't', condition: 't > 0', label: 'Taxe collectee' },
    ],
  },
  {
    eventType: 'LOAN_REPAYMENT',
    label: 'Règlement d\'échéance',
    module: 'LOAN',
    moduleLabel: 'Crédit',
    source: 'SOCLE',
    schemaCode: null,
    variables: ['principal', 'charges'],
    roles: ['settlement', 'accrued_receivable'],
    derivations: [{ name: 'p', expression: 'round(principal, 0)' }, { name: 'c', expression: 'round(charges, 0)' }, { name: 'total', expression: 'p + c' }],
    lines: [
      { account: 'PARAM:settlement', direction: 'DEBIT', amount: 'total', condition: null, label: 'Reglement d\'echeance' },
      { account: 'CONTRACT', direction: 'CREDIT', amount: 'p', condition: 'p > 0', label: 'Amortissement du capital' },
      { account: 'PARAM:accrued_receivable', direction: 'CREDIT', amount: 'c', condition: 'c > 0', label: 'Charges reglees' },
    ],
  },
  {
    eventType: 'LOAN_LATE_CHARGES',
    label: 'Intérêts de retard et pénalités',
    module: 'LOAN',
    moduleLabel: 'Crédit',
    source: 'SOCLE',
    schemaCode: null,
    variables: ['late_interest', 'penalty'],
    roles: ['accrued_receivable', 'late_interest_income', 'penalty_income'],
    derivations: [{ name: 'li', expression: 'round(late_interest, 0)' }, { name: 'pen', expression: 'round(penalty, 0)' }, { name: 'total', expression: 'li + pen' }],
    lines: [
      { account: 'PARAM:accrued_receivable', direction: 'DEBIT', amount: 'total', condition: null, label: 'Charges de retard' },
      { account: 'PARAM:late_interest_income', direction: 'CREDIT', amount: 'li', condition: 'li > 0', label: 'Interets de retard' },
      { account: 'PARAM:penalty_income', direction: 'CREDIT', amount: 'pen', condition: 'pen > 0', label: 'Penalites' },
    ],
  },
  {
    eventType: 'LOAN_PROVISION_CHARGE',
    label: 'Dotation aux provisions',
    module: 'LOAN',
    moduleLabel: 'Crédit',
    source: 'SOCLE',
    schemaCode: null,
    variables: ['amount'],
    roles: ['provision_expense', 'provision_allowance'],
    derivations: [{ name: 'booked', expression: 'round(amount, 0)' }],
    lines: [
      { account: 'PARAM:provision_expense', direction: 'DEBIT', amount: 'booked', condition: null, label: 'Dotation aux provisions' },
      { account: 'PARAM:provision_allowance', direction: 'CREDIT', amount: 'booked', condition: null, label: 'Provision pour depreciation' },
    ],
  },
  {
    eventType: 'LOAN_PROVISION_RELEASE',
    label: 'Reprise de provision',
    module: 'LOAN',
    moduleLabel: 'Crédit',
    source: 'SOCLE',
    schemaCode: null,
    variables: ['amount'],
    roles: ['provision_allowance', 'provision_release'],
    derivations: [{ name: 'booked', expression: 'round(amount, 0)' }],
    lines: [
      { account: 'PARAM:provision_allowance', direction: 'DEBIT', amount: 'booked', condition: null, label: 'Reprise de provision' },
      { account: 'PARAM:provision_release', direction: 'CREDIT', amount: 'booked', condition: null, label: 'Reprise sur provisions' },
    ],
  },
  {
    eventType: 'LOAN_INTEREST_SUSPENSION',
    label: 'Intérêts réservés',
    module: 'LOAN',
    moduleLabel: 'Crédit',
    source: 'SOCLE',
    schemaCode: null,
    variables: ['interest', 'late_interest'],
    roles: ['interest_income', 'late_interest_income', 'reserved_interest'],
    derivations: [{ name: 'i', expression: 'round(interest, 0)' }, { name: 'l', expression: 'round(late_interest, 0)' }, { name: 'total', expression: 'i + l' }],
    lines: [
      { account: 'PARAM:interest_income', direction: 'DEBIT', amount: 'i', condition: 'i > 0', label: 'Interets contractuels sortis du resultat' },
      { account: 'PARAM:late_interest_income', direction: 'DEBIT', amount: 'l', condition: 'l > 0', label: 'Interets de retard sortis du resultat' },
      { account: 'PARAM:reserved_interest', direction: 'CREDIT', amount: 'total', condition: null, label: 'Interets reserves' },
    ],
  },
  {
    eventType: 'LOAN_PREPAYMENT',
    label: 'Remboursement anticipé',
    module: 'LOAN',
    moduleLabel: 'Crédit',
    source: 'SOCLE',
    schemaCode: null,
    variables: ['principal', 'indemnity'],
    roles: ['settlement', 'prepayment_indemnity'],
    derivations: [{ name: 'capital', expression: 'round(principal, 0)' }, { name: 'indemnite', expression: 'round(indemnity, 0)' }, { name: 'total', expression: 'capital + indemnite' }],
    lines: [
      { account: 'PARAM:settlement', direction: 'DEBIT', amount: 'total', condition: null, label: 'Remboursement anticipe' },
      { account: 'CONTRACT', direction: 'CREDIT', amount: 'capital', condition: 'capital > 0', label: 'Capital rembourse par anticipation' },
      { account: 'PARAM:prepayment_indemnity', direction: 'CREDIT', amount: 'indemnite', condition: 'indemnite > 0', label: 'Indemnite de remboursement anticipe' },
    ],
  },
  {
    eventType: 'LOAN_WRITE_OFF',
    label: 'Passage en perte',
    module: 'LOAN',
    moduleLabel: 'Crédit',
    source: 'SOCLE',
    schemaCode: null,
    variables: ['principal', 'receivables', 'reserved', 'loss', 'released'],
    roles: ['accrued_receivable', 'reserved_interest', 'provision_allowance', 'write_off_loss', 'provision_release'],
    derivations: [{ name: 'capital', expression: 'round(principal, 0)' }, { name: 'creances', expression: 'round(receivables, 0)' }, { name: 'reserves', expression: 'round(reserved, 0)' }, { name: 'provision', expression: 'round(provision, 0)' }, { name: 'perte', expression: 'round(loss, 0)' }, { name: 'reprise', expression: 'round(released, 0)' }, { name: 'provision_totale', expression: 'provision + reprise' }],
    lines: [
      { account: 'CONTRACT', direction: 'CREDIT', amount: 'capital', condition: 'capital > 0', label: 'Capital sorti de l\'actif' },
      { account: 'PARAM:accrued_receivable', direction: 'CREDIT', amount: 'creances', condition: 'creances > 0', label: 'Creances sorties de l\'actif' },
      { account: 'PARAM:reserved_interest', direction: 'DEBIT', amount: 'reserves', condition: 'reserves > 0', label: 'Interets reserves imputes' },
      { account: 'PARAM:provision_allowance', direction: 'DEBIT', amount: 'provision_totale', condition: 'provision_totale > 0', label: 'Provision utilisee et reprise' },
      { account: 'PARAM:write_off_loss', direction: 'DEBIT', amount: 'perte', condition: 'perte > 0', label: 'Perte sur creance irrecouvrable' },
      { account: 'PARAM:provision_release', direction: 'CREDIT', amount: 'reprise', condition: 'reprise > 0', label: 'Provision sans objet reprise' },
    ],
  },
  {
    eventType: 'LOAN_WRITE_OFF_OFF_BALANCE',
    label: 'Passage en perte : hors bilan',
    module: 'LOAN',
    moduleLabel: 'Crédit',
    source: 'SOCLE',
    schemaCode: null,
    variables: ['amount'],
    roles: ['written_off_off_balance', 'written_off_counterpart'],
    derivations: [{ name: 'engagement', expression: 'round(amount, 0)' }],
    lines: [
      { account: 'PARAM:written_off_off_balance', direction: 'DEBIT', amount: 'engagement', condition: null, label: 'Creance passee en perte, toujours due' },
      { account: 'PARAM:written_off_counterpart', direction: 'CREDIT', amount: 'engagement', condition: null, label: 'Contrepartie du hors bilan' },
    ],
  },
  {
    eventType: 'LOAN_RECOVERY',
    label: 'Recouvrement sur créance passée en perte',
    module: 'LOAN',
    moduleLabel: 'Crédit',
    source: 'SOCLE',
    schemaCode: null,
    variables: ['amount'],
    roles: ['settlement', 'recovery_income'],
    derivations: [{ name: 'encaisse', expression: 'round(amount, 0)' }],
    lines: [
      { account: 'PARAM:settlement', direction: 'DEBIT', amount: 'encaisse', condition: null, label: 'Encaissement sur creance amortie' },
      { account: 'PARAM:recovery_income', direction: 'CREDIT', amount: 'encaisse', condition: null, label: 'Recuperation sur creance passee en perte' },
    ],
  },
  {
    eventType: 'LOAN_RECOVERY_OFF_BALANCE',
    label: 'Recouvrement : extourne du hors bilan',
    module: 'LOAN',
    moduleLabel: 'Crédit',
    source: 'SOCLE',
    schemaCode: null,
    variables: ['amount'],
    roles: ['written_off_counterpart', 'written_off_off_balance'],
    derivations: [{ name: 'engagement', expression: 'round(amount, 0)' }],
    lines: [
      { account: 'PARAM:written_off_counterpart', direction: 'DEBIT', amount: 'engagement', condition: null, label: 'Contrepartie du hors bilan' },
      { account: 'PARAM:written_off_off_balance', direction: 'CREDIT', amount: 'engagement', condition: null, label: 'Creance recouvree, sortie du hors bilan' },
    ],
  },
  {
    eventType: 'FEE_CHARGE',
    label: 'Perception d\'une commission',
    module: 'FEE',
    moduleLabel: 'Commissions',
    source: 'PARAMETRABLE',
    schemaCode: 'FEE_STANDARD',
    variables: ['net', 'tax'],
    roles: ['fee_income', 'fee_tax'],
    derivations: [{ name: 'net_booked', expression: 'round(net, 0)' }, { name: 'tax_booked', expression: 'round(tax, 0)' }, { name: 'total', expression: 'net_booked + tax_booked' }],
    lines: [
      { account: 'CONTRACT', direction: 'DEBIT', amount: 'total', condition: null, label: 'Commission' },
      { account: 'PARAM:fee_income', direction: 'CREDIT', amount: 'net_booked', condition: null, label: 'Produit de commission' },
      { account: 'PARAM:fee_tax', direction: 'CREDIT', amount: 'tax_booked', condition: 'tax_booked > 0', label: 'Taxe collectee' },
    ],
  },
];
